### ISSUE TITLE
Expand properties for collected resource information

### ISSUE THREAD

**Issue by BernieWhite** [JulianHayward/Azure-MG-Sub-Governance-Reporting#149]
For PSRule for Azure to evaluate many rules `properties` must be able to be inspected for each resource. For example:

The property `properties.sslEnforcement` need to be inspected to determine if it set to `Enabled`.

```yaml
---
# Synopsis: Enforce encrypted PostgreSQL connections.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.PostgreSQL.UseSSL
  ref: AZR-000147
  tags:
    release: 'GA'
    ruleSet: '2020_06'
    Azure.WAF/pillar: 'Security'
  labels:
    Azure.ASB.v3/control: 'NS-2'
spec:
  type:
  - Microsoft.DBforPostgreSQL/servers
  condition:
    field: properties.sslEnforcement
    equals: Enabled
```

Currently the get API only retrieves the resource itself without the `properties` property.

https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/74363de2e51343864fffc9ddab5792dfc9e863da/pwsh/AzGovVizParallel.ps1#L28264

Because we need to do this based the resource provider API version I propose we:

- Get each resource provider API version.
- Get each resource via resource ID using the latest API version reported by the resource provider.

Thoughts?

---

Related to PSRule for Azure issues:

- https://github.com/Azure/PSRule.Rules.Azure/issues/1914
- https://github.com/Azure/PSRule.Rules.Azure/issues/1919
