### ISSUE TITLE
SubscriptionQuotaWhitelist fails with more than one entry

### ISSUE THREAD

**Issue by Ben424242** [JulianHayward/Azure-MG-Sub-Governance-Reporting#92]
# Describe the bug

When I add two whitelisted quota IDs to the AzGovViz.variables.yml file the report finds no matching subscriptions. If I use either one of the parameters by itself I get the expected result from the pipeline.

# To Reproduce

Use this code in the AzGovViz.variables.yml file:

```
# Processes only Subscriptions that startWith the given QuotaIds
  - name: SubscriptionQuotaIdWhitelistParameters
    type: object
    # example:
    #   default:
    #     - MSDN_
    #     - EnterpriseAgreement_
    default:
      - EnterpriseAgreement_
      - MSDNDevTest_
    
 ```

# Additional context

In the pipeline when the "Create Arguments String" step runs it puts single quotes around all the argument values in the argument string. Putting those single quotes around the values for SubscriptionQuotaIdWhitelist parameter makes the script treat it like a string instead of an array. 

I hacked the pipeline to force an argument string that didn't have the single quotes around the whitelisted subs and it worked.

Not working:

Build Script Arguments String...

Arguments String: -ManagementGroupId '00a9f7b2-9733-42fa-9b43-3ffc9f5d132d' -CsvDelimiter ';' -OutputPath 'wiki' -SubscriptionQuotaIdWhitelist 'EnterpriseAgreement_, MSDNDevTest_' ...

Working:

Build Script Arguments String...

Arguments String: -ManagementGroupId '00a9f7b2-9733-42fa-9b43-3ffc9f5d132d' -CsvDelimiter ';' -OutputPath 'wiki' -SubscriptionQuotaIdWhitelist EnterpriseAgreement_, MSDNDevTest_ ...
